Resources:
  ClarvoDocumentProcessorFunction:   # <-- this is what you use in commands
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: clarvoDocumentProcessor
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      Timeout: 180   # add or increase this (seconds)