AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: python3.12
    Timeout: 60
    MemorySize: 128

Resources:
  ClarvoDocumentProcessorFunction: # <-- this is what you use in commands
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: clarvoDocumentProcessor
      Handler: lambda.clarvoDocumentProcessor.lambda_handler

  ClarvoBedrockAgentRetriever: # <-- this is what you use in commands
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: clarvoBedrockAgentRetriever
      Handler: lambda.clarvoBedrockAgentRetriever.lambda_handler

  ClarvoKBSync: # <-- this is what you use in commands
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: clarvoKBSync
      Handler: lambda.clarvoKBSync.lambda_handler

  ClarvoDDB: # <-- this is what you use in commands
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: clarvoBedrockAgentRetriever
      Handler: lambda.query_db.lambda_handler
